update dispatch yml

diff --git a/.github/workflows/playwright_dispatch_run.yml b/.github/workflows/playwright_dispatch_run.yml
--- a/.github/workflows/playwright_dispatch_run.yml
+++ b/.github/workflows/playwright_dispatch_run.yml
@@ -25,7 +25,7 @@ jobs:
       INT_REALM_US_BASE_URL: ${{vars.INT_REALM_US_BASE_URL}}
       S3_BUCKET: ${{vars.S3_BUCKET}}
       CI_ENV: ${{vars.CI_ENV}}
-      ENV: ${{ github.event.inputs.environment }}
+      ENVIRONMENT: ${{ github.event.inputs.environment }}
 
     steps:
       - name: Checkout repository
@@ -64,18 +64,62 @@ jobs:
       # - name: List allure results
       #   run: ls -alh allure-results
 
-      - name: Upload Allure results for ${{ env.ENV  }} -shard ${{ matrix.shard }}
+      - name: Upload Allure results for ${{ env.ENVIRONMENT  }} -shard ${{ matrix.shard }}
         uses: actions/upload-artifact@v4
         with:
-          name: allure-results-${{ env.ENV  }}-${{ matrix.shard }}
+          name: allure-results-${{ env.ENVIRONMENT  }}-${{ matrix.shard }}
           path: allure-results
+    outputs:
+      test-environment: ${{ env.ENVIRONMENT }}
+
+  copy_old_history:
+    runs-on: ubuntu-latest
+    needs: test
+    env:
+      ENVIRONMENT: ${{ needs.test.outputs.test-environment }}
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Checkout gh-pages branch
+        run: |
+          git fetch origin gh-pages
+          git checkout gh-pages
+
+      - name: Copy Allure History
+        run: |
+          if [ -d "docs/${{ env.ENVIRONMENT }}/allure-report-${{ env.ENVIRONMENT }}/history" ]; then
+            mkdir -p allure-results/history
+            cp -R docs/${{ env.ENVIRONMENT }}/allure-report-${{ env.ENVIRONMENT }}/history/* allure-results/history/
+          else
+            echo "No history found from gh-pages."
+          fi
+
+      - name: Upload Old Allure report History
+        uses: actions/upload-artifact@v4
+        with:
+          name: old_allure-history-${{ env.ENVIRONMENT }}
+          path: allure-results/history
+
+        continue-on-error: true
+
+      - name: Checkout main branch
+        run: |
+          git checkout main
+
+    outputs:
+      copy_old_history-environment: ${{ env.ENVIRONMENT }}          
+          
 
   merge_results:
     runs-on: ubuntu-latest
-    needs: test
+    needs: copy_old_history
 
     env:
-      ENV: ${{ github.event.inputs.environment }}
+      ENVIRONMENT: ${{ needs.copy_old_history.outputs. copy_old_history-environment }}
 
     steps:
       - name: Checkout repository
@@ -84,29 +128,29 @@ jobs:
       - name: Download Allure results from all shards
         uses: actions/download-artifact@v4
         with:
-          name: allure-results-${{ env.ENV  }}-1
-          path: allure-results-${{ env.ENV  }}/1
+          name: allure-results-${{ env.ENVIRONMENT }}-1
+          path: allure-results-${{ env.ENVIRONMENT }}/1
         continue-on-error: true
 
       - name: Download Allure results from all shards
         uses: actions/download-artifact@v4
         with:
-          name: allure-results-${{ env.ENV }}-2
-          path: allure-results-${{ env.ENV }}/2
+          name: allure-results-${{ env.ENVIRONMENT}}-2
+          path: allure-results-${{ env.ENVIRONMENT}}/2
         continue-on-error: true
 
       - name: Download Allure results from all shards
         uses: actions/download-artifact@v4
         with:
-          name: allure-results-${{ env.ENV  }}-3
-          path: allure-results-${{ env.ENV  }}/3
+          name: allure-results-${{ env.ENVIRONMENT }}-3
+          path: allure-results-${{ env.ENVIRONMENT }}/3
         continue-on-error: true
 
       - name: Download Allure results from all shards
         uses: actions/download-artifact@v4
         with:
-          name: allure-results-${{ env.ENV  }}-4
-          path: allure-results-${{ env.ENV  }}/4
+          name: allure-results-${{ env.ENVIRONMENT }}-4
+          path: allure-results-${{ env.ENVIRONMENT }}/4
         continue-on-error: true
 
       - name: Install allure-commandline
@@ -119,27 +163,29 @@ jobs:
         run: |
           mkdir -p allure-results/combined
           # Combine results from all shards into a single directory
-          cp -r allure-results-${{ env.ENV  }}/1/* allure-results/combined/ || true
-          cp -r allure-results-${{ env.ENV  }}/2/* allure-results/combined/ || true
-          cp -r allure-results-${{ env.ENV  }}/3/* allure-results/combined/ || true
-          cp -r allure-results-${{ env.ENV  }}/4/* allure-results/combined/ || true
+          cp -r allure-results-${{ env.ENVIRONMENT }}/1/* allure-results/combined/ || true
+          cp -r allure-results-${{ env.ENVIRONMENT }}/2/* allure-results/combined/ || true
+          cp -r allure-results-${{ env.ENVIRONMENT }}/3/* allure-results/combined/ || true
+          cp -r allure-results-${{ env.ENVIRONMENT }}/4/* allure-results/combined/ || true
+          # Include the previous history
+          cp -r old_allure-history-${{ env.ENVIRONMENT }} allure-results/combined/history || true
           # Generate the Allure report
-          npx allure generate allure-results/combined --clean -o allure-report-${{ env.ENV  }}
+          npx allure generate allure-results/combined --clean -o allure-report-${{ env.ENVIRONMENT }}
           # List contents of the report directory for debugging
-          ls -alh allure-report-${{ env.ENV  }}
+          ls -alh allure-report-${{ env.ENVIRONMENT }}
 
       - name: Upload Allure Report
         uses: actions/upload-artifact@v4
         with:
-          name: allure-report-${{ env.ENV  }}
-          path: allure-report-${{ env.ENV  }}
+          name: allure-report-${{ env.ENVIRONMENT }}
+          path: allure-report-${{ env.ENVIRONMENT }}
 
   deploy:
     runs-on: ubuntu-latest
     needs: merge_results
     if: always()
     env:
-      ENV: ${{ github.event.inputs.environment }}
+      ENVIRONMENT: ${{ github.event.inputs.environment }}
 
     steps:
       - name: Checkout repository
@@ -164,31 +210,31 @@ jobs:
         # Clean only the folder for the current environment being run
       - name: Clean up the current environment's report folder
         run: |
-          if [ -d "docs/${{ env.ENV }}" ]; then
-            echo "Cleaning up folder docs/${{ env.ENV }}"
-            find docs/${{ env.ENV }} -mindepth 1 -exec rm -rf {} +
+          if [ -d "docs/${{ env.ENVIRONMENT }}" ]; then
+            echo "Cleaning up folder docs/${{ env.ENVIRONMENT }}"
+            find docs/${{ env.ENVIRONMENT }} -mindepth 1 -exec rm -rf {} +
           else
-            echo "Directory docs/${{ env.ENV }} does not exist, skipping cleanup"
+            echo "Directory docs/${{ env.ENVIRONMENT }} does not exist, skipping cleanup"
           fi
 
       - name: Verify docs Directory after cleanup
         run: |
           echo "docs directory contents after cleanup:"
           ls -alh docs
-          ls -alh docs/${{ env.ENV }} || echo "docs/${{ env.ENV }} directory not found"
+          ls -alh docs/${{ env.ENVIRONMENT }} || echo "docs/${{ env.ENVIRONMENT }} directory not found"
               
         # Download the Allure report for the current environment
       - name: Download Allure Report
         uses: actions/download-artifact@v4
         with:
-          name: allure-report-${{ env.ENV }}
-          path: docs/${{ env.ENV }}/allure-report-${{ env.ENV }} 
+          name: allure-report-${{ env.ENVIRONMENT }}
+          path: docs/${{ env.ENVIRONMENT }}/allure-report-${{ env.ENVIRONMENT }} 
 
 
           # List new report after download
       - name: List new report after download
         run: |
-          ls -alh docs/${{ env.ENV }}
+          ls -alh docs/${{ env.ENVIRONMENT }}
 
       - name: Check git status
         run: |
@@ -201,8 +247,8 @@ jobs:
       # Add and commit the changes to gh-pages
       - name: Add and Commit the new report
         run: |
-          git add docs/${{ env.ENV }}/allure-report-${{ env.ENV }}
-          git commit -m "Update Allure report for ${{ env.ENV }}" || echo "No changes to commit"
+          git add docs/${{ env.ENVIRONMENT }}/allure-report-${{ env.ENVIRONMENT }}
+          git commit -m "Update Allure report for ${{ env.ENVIRONMENT }}" || echo "No changes to commit"
 
       # Push the changes to the gh-pages branch
       - name: Push changes to gh-pages
