Update cron update condition FIX

diff --git a/.github/workflows/playwrightCI.yml b/.github/workflows/playwrightCI.yml
--- a/.github/workflows/playwrightCI.yml
+++ b/.github/workflows/playwrightCI.yml
@@ -2,14 +2,14 @@ name: CI PUSH & SCHEDULED Run Playwright Tests
 
 on:
   schedule:
-    - cron: "25 18 * * *"
-    - cron: "20 18 * * *"
-      
-  push:
-    branches: [main, develop]
-  pull_request:
-    branches:
-      - "main"
+    - cron: "45 18 * * *"
+    - cron: "50 18 * * *"
+
+  # push:
+  #   branches: [main, develop]
+  # pull_request:
+  #   branches:
+  #     - "main"
 
 jobs:
   test:
@@ -41,10 +41,10 @@ jobs:
         id: set-env
         run: |
           if [ ${{ github.event_name }} == "schedule" ]; then
-            if [ ${{ github.event.schedule }} == "25 18 * * *" ]; then
-              ENVIRONMENT="dev"
-            elif [ "${{ github.event.schedule }}" == "20 18 * * *" ]; then
+            if [ ${{ github.event.schedule }} == '45 18 * * *' ]; then
               ENVIRONMENT="int"
+            elif [ "${{ github.event.schedule }}" == '50 18 * * *' ]; then
+              ENVIRONMENT="dev"
             fi
           elif [ ${{ github.event_name }} == "push" ]; then
             if [ ${{ github.ref }} == "refs/heads/main" ]; then
@@ -56,7 +56,7 @@ jobs:
 
           echo "ENVIRONMENT=$ENVIRONMENT"
           # echo "::set-output name=environment::$ENVIRONMENT"  # Set the environment as output 
-          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT  # Set the environment as output   
+          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT  # Set the environment as output
 
       - name: Setup Node.js
         uses: actions/setup-node@v4
@@ -96,13 +96,12 @@ jobs:
           name: allure-results-${{ steps.set-env.outputs.environment }}-${{ matrix.shard }}
           path: allure-results
 
-
   merge_results:
     runs-on: ubuntu-latest
     needs: test
 
     env:
-       ENVIRONMENT: ${{ needs.test.outputs.environment }}
+      ENVIRONMENT: ${{ needs.test.outputs.environment }}
 
     # strategy:
     #   matrix:
@@ -166,7 +165,7 @@ jobs:
         with:
           name: allure-report-${{ env.ENVIRONMENT }}
           path: allure-report-${{ env.ENVIRONMENT }}
-    
+
     outputs:
       merged-environment: ${{ env.ENVIRONMENT }}
 
@@ -200,13 +199,13 @@ jobs:
           git checkout gh-pages || git checkout -b gh-pages
 
       # - name: Verify .git directory exists before cleanup
-      #   run: | 
-      #     if [ -d ".git" ]; then 
-      #       echo ".git directory found"; 
-      #       ls -la .git; 
-      #     else 
-      #       echo ".git directory not found"; 
-      #       exit 1; 
+      #   run: |
+      #     if [ -d ".git" ]; then
+      #       echo ".git directory found";
+      #       ls -la .git;
+      #     else
+      #       echo ".git directory not found";
+      #       exit 1;
       #     fi
 
       # Clean up all files except docs and .git
@@ -236,8 +235,8 @@ jobs:
             find docs/${{ env.ENVIRONMENT }} -mindepth 1 -exec rm -rf {} +
           else
             echo "Directory docs/${{ env.ENVIRONMENT }} does not exist, skipping cleanup"
-          fi   
-      
+          fi
+
       - name: Verify docs Directory after cleanup
         run: |
           echo "docs directory contents after cleanup:"
@@ -249,7 +248,7 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: allure-report-${{ env.ENVIRONMENT }}
-          path: docs/${{ env.ENVIRONMENT }}/allure-report-${{ env.ENVIRONMENT }}  
+          path: docs/${{ env.ENVIRONMENT }}/allure-report-${{ env.ENVIRONMENT }}
 
       # List new report after download
       - name: List new report after download
